INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (1, 2, 2 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (2, 1, 3 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (3, 5, 32 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (4, 4, 31 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (5, 3, 12 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (6, 6, 11 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (7, 7, 15 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (8, 8, 16 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (9, 9, 17 )
INSERT INTO `user_accounts`.`account` (`account_id`, `user_id`, `account`) VALUES (10, 10, 18 )

INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (1, 'artsiom', 'kuzmik')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (2, 'hello', 'iam')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (3, 'andrew', 'valgam')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (4, 'Denis', 'Herea')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (5, 'Locj', 'Faneev')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (6, 'Petr', 'Vasiol')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (7, 'Holen', 'Jock')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (8, 'Alina', 'Kuzmik')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (9, 'Kirol', 'Olegs')
INSERT INTO `user_accounts`.`user` (`id`, `name`, `surname`) VALUES (10, 'Valen', 'Pojekush')